dependencies {
  api("com.badlogicgames.gdx:gdx:${project.property("gdxVersion")}")
  api("com.badlogicgames.gdx:gdx-box2d:${project.property("gdxVersion")}")
  api("com.badlogicgames.ashley:ashley:${project.property("ashleyVersion")}")
  api("com.badlogicgames.gdx:gdx-ai:${project.property("aiVersion")}")
  api("com.badlogicgames.gdx-controllers:gdx-controllers-core:${project.property("gdxControllersVersion")}")
  api("org.jetbrains.kotlinx:kotlinx-coroutines-core:${project.property("coroutines")}")
  implementation(kotlin("reflect"))
  api("io.github.libktx:ktx-app:${project.property("ktxVersion")}")
  api("io.github.libktx:ktx-ashley:${project.property("ktxVersion")}")
  api("io.github.libktx:ktx-box2d:${project.property("ktxVersion")}")
  api("io.github.libktx:ktx-assets-async:${project.property("ktxVersion")}")
  api("io.github.libktx:ktx-collections:${project.property("ktxVersion")}")
  api("io.github.libktx:ktx-graphics:${project.property("ktxVersion")}")
  api("io.github.libktx:ktx-log:${project.property("ktxVersion")}")
  api("io.github.libktx:ktx-tiled:${project.property("ktxVersion")}")
}
